eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
# microservice:
#   paymentservice:
#     endpoints:
#       endpoint:
#         uri: http://PAYMENT-SERVICE/api/payment
#   orderservice:
#     endpoints:
#       endpoint:
#         uri: http://ORDER-SERVICE/api/order

# microservice.paymentservice.endpoints.endpoint.uri: http://PAYMENT-SERVICE/api/payment
paymentservice: http://PAYMENT-SERVICE/api/payment
orderservice: http://ORDER-SERVICE/api/order
